targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options for json_serializable
          create_to_json: true
          create_factory: true
      riverpod_generator:
        options:
          # Options for riverpod_generator
